### ISSUE TITLE
Call to peek() Fails

### ISSUE THREAD

**Issue by KirbyJames** [salabim/peek#4]
Hi,

I've installed peek under the current version of Anaconda python on Windows 11.
I've tried running this minimal program 

```
from peek import peek

peek()

```
and get the following error

```
python test_peek.py
Traceback (most recent call last):
  File "C:\Users\kirby\Dropbox\python\utilities\test_peek.py", line 6, in <module>
    peek()
  File "C:\Users\kirby\anaconda3\Lib\site-packages\peek\peek.py", line 658, in __call__
    no_source_error()
  File "C:\Users\kirby\anaconda3\Lib\site-packages\peek\peek.py", line 349, in no_source_error
    raise NotImplementedError(
NotImplementedError:
```

What am I doing wrong?

**Comment by KirbyJames** [comment]
And using testPeek.py I get

```
python test_peek2.py
================================================= test session starts =================================================
platform win32 -- Python 3.11.5, pytest-7.4.0, pluggy-1.0.0 -- C:\Users\kirby\anaconda3\python.exe
cachedir: .pytest_cache
rootdir: C:\Users\kirby\Dropbox\python\utilities
plugins: anyio-3.5.0
collected 43 items

test_peek2.py::test_time FAILED

====================================================== FAILURES =======================================================
______________________________________________________ test_time ______________________________________________________

patch_datetime_now = None

    def test_time(patch_datetime_now):
        hello = "world"
>       s = peek(hello, show_time=True, as_str=True)

test_peek2.py:45:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
..\..\..\anaconda3\Lib\site-packages\peek\peek.py:1018: in __call__
    return peek(*args, **kwargs)
..\..\..\anaconda3\Lib\site-packages\peek\peek.py:658: in __call__
    no_source_error()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

s = None

    def no_source_error(s=None):
        if s is not None:
            print(s)  # for debugging only
>       raise NotImplementedError(
            """
    Failed to access the underlying source code for analysis. Possible causes:
    - decorated function/method definition spawns more than one line
    - used from a frozen application (e.g. packaged with PyInstaller)
    - underlying source code was changed during execution"""
        )
E       NotImplementedError:
E       Failed to access the underlying source code for analysis. Possible causes:
E       - decorated function/method definition spawns more than one line
E       - used from a frozen application (e.g. packaged with PyInstaller)
E       - underlying source code was changed during execution

..\..\..\anaconda3\Lib\site-packages\peek\peek.py:349: NotImplementedError
=============================================== short test summary info ===============================================
FAILED test_peek2.py::test_time - NotImplementedError:
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! stopping after 1 failures !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
================================================== 1 failed in 0.48s ==================================================

```

**Comment by salabim** [comment]
Are you trying to run from a REPL or notebook?

**Comment by KirbyJames** [comment]
No I'm running python from a command line prompt.  e.g.
>python test_peek.py

**Comment by salabim** [comment]
What happens if you run this minimal program:
```
import peek
peek(1)
```
?
So, not test_peek.py.

**Comment by KirbyJames** [comment]
It behaves the same 

```
>type test_peek3.py
#   test_peek3.py

from peek import peek

peek(1)

>
>python test_peek3.py
Traceback (most recent call last):
  File "D:\Dropbox\python\utilities\test_peek3.py", line 5, in <module>
    peek(1)
  File "C:\Users\kirby\Anaconda3\Lib\site-packages\peek\peek.py", line 660, in __call__
    no_source_error()
  File "C:\Users\kirby\Anaconda3\Lib\site-packages\peek\peek.py", line 349, in no_source_error
    raise NotImplementedError(
NotImplementedError:
Failed to access the underlying source code for analysis. Possible causes:
- decorated function/method definition spawns more than one line
- used from a frozen application (e.g. packaged with PyInstaller)
- underlying source code was changed during execution
- 
```

**Comment by salabim** [comment]
Strange.

Can you try the code below icecream (the inspirator of peek)?
pip install icecream
```
from icecream import ic
ic(1)
```

**Comment by KirbyJames** [comment]
```
>pip install icecream
Collecting icecream
  Obtaining dependency information for icecream from https://files.pythonhosted.org/packages/06/4e/21e309c7087695cf500a1827597f8510641f2c9a50ed7741bf7fc38736ff/icecream-2.1.3-py2.py3-none-any.whl.metadata
  Downloading icecream-2.1.3-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: colorama>=0.3.9 in c:\users\kirby\anaconda3\lib\site-packages (from icecream) (0.4.6)
Requirement already satisfied: pygments>=2.2.0 in c:\users\kirby\anaconda3\lib\site-packages (from icecream) (2.15.1)
Requirement already satisfied: executing>=0.3.1 in c:\users\kirby\anaconda3\lib\site-packages (from icecream) (0.8.3)
Requirement already satisfied: asttokens>=2.0.1 in c:\users\kirby\anaconda3\lib\site-packages (from icecream) (2.0.5)
Requirement already satisfied: six in c:\users\kirby\anaconda3\lib\site-packages (from asttokens>=2.0.1->icecream) (1.16.0)
Downloading icecream-2.1.3-py2.py3-none-any.whl (8.4 kB)
Installing collected packages: icecream
Successfully installed icecream-2.1.3

>type test_peek5.py
#   test_peek5.py

from icecream import ic

ic(1)

>
>python test_peek5.py
ic| Error: Failed to access the underlying source code for analysis. Was ic() invoked in a REPL (e.g. from the command line), a frozen application (e.g. packaged with PyInstaller), or did the underlying source code change during execution?

>

```

**Comment by KirbyJames** [comment]
https://github.com/gruns/icecream/issues/160 ?

**Comment by salabim** [comment]
It looks like that's the same problem.
And yet icecream has thousands of users ...
So, you must have a special installation. Is reinstalling of Python an option?

**Comment by salabim** [comment]
I just realize that it might have to do with the version of the executing or asttokens module.
Could you try
pip install executing --upgrade
pip install asttokens --upgrade
?

**Comment by KirbyJames** [comment]
I upgraded Python from 3.11.5 to 3.11.10 - which made no difference (still errors)

But the two upgrades made the difference - it now works as expected - many thanks !!

```
>pip install executing --upgrade
Requirement already satisfied: executing in c:\users\kirby\anaconda3\lib\site-packages (0.8.3)
Collecting executing
  Obtaining dependency information for executing from https://files.pythonhosted.org/packages/b5/fd/afcd0496feca3276f509df3dbd5dae726fcc756f1a08d9e25abe1733f962/executing-2.1.0-py2.py3-none-any.whl.metadata
  Downloading executing-2.1.0-py2.py3-none-any.whl.metadata (8.9 kB)
Downloading executing-2.1.0-py2.py3-none-any.whl (25 kB)
Installing collected packages: executing
  Attempting uninstall: executing
    Found existing installation: executing 0.8.3
    Uninstalling executing-0.8.3:
      Successfully uninstalled executing-0.8.3
Successfully installed executing-2.1.0

(base) D:\Dropbox\python\utilities>pip install asttokens --upgrade
Requirement already satisfied: asttokens in c:\users\kirby\anaconda3\lib\site-packages (2.0.5)
Collecting asttokens
  Obtaining dependency information for asttokens from https://files.pythonhosted.org/packages/25/8a/c46dcc25341b5bce5472c718902eb3d38600a903b14fa6aeecef3f21a46f/asttokens-3.0.0-py3-none-any.whl.metadata
  Downloading asttokens-3.0.0-py3-none-any.whl.metadata (4.7 kB)
Downloading asttokens-3.0.0-py3-none-any.whl (26 kB)
Installing collected packages: asttokens
  Attempting uninstall: asttokens
    Found existing installation: asttokens 2.0.5
    Uninstalling asttokens-2.0.5:
      Successfully uninstalled asttokens-2.0.5
Successfully installed asttokens-3.0.0


>python  test_peek2.py
================================================= test session starts =================================================
platform win32 -- Python 3.11.10, pytest-7.4.4, pluggy-1.5.0 -- C:\Users\kirby\Anaconda3\python.exe
cachedir: .pytest_cache
rootdir: D:\Dropbox\python\utilities
plugins: anyio-4.6.2
collected 43 items

test_peek2.py::test_time PASSED
test_peek2.py::test_no_arguments PASSED
test_peek2.py::test_one_arguments PASSED
test_peek2.py::test_two_arguments PASSED
test_peek2.py::test_in_function PASSED
test_peek2.py::test_in_function_no_parent PASSED
test_peek2.py::test_prefix PASSED
test_peek2.py::test_time_delta PASSED
test_peek2.py::test_dynamic_prefix PASSED
test_peek2.py::test_values_only PASSED
test_peek2.py::test_calls PASSED
test_peek2.py::test_output PASSED
test_peek2.py::test_clone PASSED
test_peek2.py::test_sort_dicts PASSED
test_peek2.py::test_underscore_numbers PASSED
test_peek2.py::test_multiline PASSED
test_peek2.py::test_decorator PASSED
test_peek2.py::test_decorator_edge_cases PASSED
test_peek2.py::test_decorator_with_methods PASSED
test_peek2.py::test_read_toml1 PASSED
test_peek2.py::test_context_manager PASSED
test_peek2.py::test_return_none PASSED
test_peek2.py::test_wrapping PASSED
test_peek2.py::test_compact PASSED
test_peek2.py::test_depth_indent PASSED
test_peek2.py::test_enabled PASSED
test_peek2.py::test_enabled2 PASSED
test_peek2.py::test_level PASSED
test_peek2.py::test_multiple_as PASSED
test_peek2.py::test_wrap_indent PASSED
test_peek2.py::test_traceback PASSED
test_peek2.py::test_enforce_line_length PASSED

```

**Comment by salabim** [comment]
I have added the latest versions in the requirements of peek.
Thanks to you, peek is now more stable.
